name: MSBuild

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [ Win32, x64, ARM64 ]
      fail-fast: false
    steps:
    - name: Checkout zlib
      uses: actions/checkout@v4
      with:
        path: zlib
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: msbuild /t:zlibstat /p:Configuration=ReleaseWithoutAsm /p:Platform=${{ matrix.architecture }} ${{ github.workspace }}\zlib\contrib\vstudio\vc17\zlibvc.sln /verbosity:quiet /warnaserror
